#ifndef _H_pixmaps
#define _H_pixmaps


/*  Tiles:
*/
#include "images/empty.xpm"
#include "images/floor-and-ladder.xpm"
#include "images/floor.xpm"
#include "images/ladder.xpm"
#include "images/plate.xpm"


/*  Sprite images:
*/
#include "images/chef-front0.xpm"
#include "images/chef-front1.xpm"
#include "images/chef-front2.xpm"
#include "images/chef-back0.xpm"
#include "images/chef-back1.xpm"
#include "images/chef-back2.xpm"
#include "images/chef-left0.xpm"
#include "images/chef-left1.xpm"
#include "images/chef-left2.xpm"
#include "images/chef-right0.xpm"
#include "images/chef-right1.xpm"
#include "images/chef-right2.xpm"
#include "images/chef-dead0.xpm"
#include "images/chef-dead1.xpm"
#include "images/chef-dead2.xpm"
#include "images/chef-dead3.xpm"
#include "images/chef-dead4.xpm"
#include "images/chef-dead5.xpm"

#include "images/egg-front0.xpm"
#include "images/egg-front1.xpm"
#include "images/egg-back0.xpm"
#include "images/egg-back1.xpm"
#include "images/egg-left0.xpm"
#include "images/egg-left1.xpm"
#include "images/egg-right0.xpm"
#include "images/egg-right1.xpm"
#include "images/egg-dead0.xpm"
#include "images/egg-dead1.xpm"
#include "images/egg-dead2.xpm"
#include "images/egg-dead3.xpm"
#include "images/egg-peppered0.xpm"
#include "images/egg-peppered1.xpm"

#include "images/hotdog-front0.xpm"
#include "images/hotdog-front1.xpm"
#include "images/hotdog-back0.xpm"
#include "images/hotdog-back1.xpm"
#include "images/hotdog-left0.xpm"
#include "images/hotdog-left1.xpm"
#include "images/hotdog-right0.xpm"
#include "images/hotdog-right1.xpm"
#include "images/hotdog-dead0.xpm"
#include "images/hotdog-dead1.xpm"
#include "images/hotdog-dead2.xpm"
#include "images/hotdog-dead3.xpm"
#include "images/hotdog-peppered0.xpm"
#include "images/hotdog-peppered1.xpm"

#include "images/pickle-front0.xpm"
#include "images/pickle-front1.xpm"
#include "images/pickle-back0.xpm"
#include "images/pickle-back1.xpm"
#include "images/pickle-left0.xpm"
#include "images/pickle-left1.xpm"
#include "images/pickle-right0.xpm"
#include "images/pickle-right1.xpm"
#include "images/pickle-dead0.xpm"
#include "images/pickle-dead1.xpm"
#include "images/pickle-dead2.xpm"
#include "images/pickle-dead3.xpm"
#include "images/pickle-peppered0.xpm"
#include "images/pickle-peppered1.xpm"

#include "images/top-bun0.xpm"
#include "images/top-bun1.xpm"
#include "images/top-bun2.xpm"
#include "images/top-bun3.xpm"
#include "images/lettuce0.xpm"
#include "images/lettuce1.xpm"
#include "images/lettuce2.xpm"
#include "images/lettuce3.xpm"
#include "images/redstuff0.xpm"
#include "images/redstuff1.xpm"
#include "images/redstuff2.xpm"
#include "images/redstuff3.xpm"
#include "images/yellowstuff0.xpm"
#include "images/yellowstuff1.xpm"
#include "images/yellowstuff2.xpm"
#include "images/yellowstuff3.xpm"
#include "images/meat0.xpm"
#include "images/meat1.xpm"
#include "images/meat2.xpm"
#include "images/meat3.xpm"
#include "images/bottom-bun0.xpm"
#include "images/bottom-bun1.xpm"
#include "images/bottom-bun2.xpm"
#include "images/bottom-bun3.xpm"

#include "images/pepper0.xpm"
#include "images/pepper1.xpm"

#include "images/icecream.xpm"
#include "images/coffee.xpm"
#include "images/fries.xpm"

#include "images/digit0.xpm"
#include "images/digit1.xpm"
#include "images/digit2.xpm"
#include "images/digit3.xpm"
#include "images/digit4.xpm"
#include "images/digit5.xpm"
#include "images/digit6.xpm"
#include "images/digit7.xpm"
#include "images/digit8.xpm"
#include "images/digit9.xpm"


#endif  /* _H_pixmaps */
